# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Check out the repo to copy the file from
        uses: actions/checkout@master
        with:
          repository: orgname/reponame
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! Hope this ran because of the other repo
      - name: update schema files
        run: |
          ls
          git config user.name 'ryandillinfelton' 
          git config user.email 'rfelton@redhat.com'
          echo beans > new_file.txt
          git add -A
          git commit -m "update"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
